/* action creators  constants */

export const TOGGLE_SEARCH_BAR = 'TOGGLE_SEARCH_BAR';

// SHOW PRIZE LIST WHEN COMPONENT WILL MOUNT...
export const ALL_PRIZES = 'ALL_PRIZES';
export const ALL_PRIZES_SUCCESS = 'ALL_PRIZES_SUCCESS';
export const ALL_PRIZES_ERROR = 'ALL_PRIZES_ERROR';

// SEARCH PRIZES BY TITLE  FROM PRIZES API
export const SHOW_PRIZES = 'SHOW_PRIZES';

// GET ALL PRIZES FORM GETPRIZE BY ID API...
export const GET_HIDDEN_PRIZES = 'GET_HIDDEN_PRIZES';
export const GET_HIDDEN_PRIZES_SUCCESS = 'GET_HIDDEN_PRIZES_SUCCESS';
export const GET_HIDDEN_PRIZES_ERROR = 'GET_HIDDEN_PRIZES_ERROR';

// SORT DATA FROM PRIZES API ....
export const SORT_TYPE = 'SORT_TYPE';

// DTATA FILTERING BY TYPE FROM PRIZES API...
export const FILTER_TYPE = 'FILTER_TYPE';

// DATA FROM API FOR ADVERTISEMENT SECTION...
export const FETCH_ADVERTS = 'FETCH_ADVERTS';
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS';
export const FETCH_ADVERTS_ERROR = 'FETCH_ADVERTS_ERROR';

// DATAT FROM API PRIZES FOR PRIZE DETAILS BY ID....
export const FETCH_PRIZE_BY_ID = 'FETCH_PRIZE_BYID';
export const FETCH_PRIZE_BY_ID_SUCCESS = 'FETCH_PRIZE_BY_ID_SUCCESS';
export const FETCH_PRIZES_BY_ID_ERROR = 'FETCH_PRIZE_BY_ID_ERROR';

// export const BASE_URL = "https://www.art-prizes.com";
// export function ALL_PRIZES(token) {
//   return "/api/ArtPrizes/" + token;
// }

// SHOW EXHIBITION LIST WHEN COMPONENT WILL MOUNT ..... FROM EXHIBITION API......

export const ALL_EXHIBITIONS = 'ALL_EXHIBITIONS';
export const ALL_EXHIBITIONS_SUCCESS = 'ALL_EXHIBITIONS_SUCCESS';
export const ALL_EXHIBITIONS_ERROR = 'ALL_EXHIBITIONS_ERROR';

// SEARCH PRIZES BY TITLE IN EXHIBITIONS API
export const SHOW_EXHIBITIONS = 'SHOW_EXHIBITIONS';

// SORT PRIZES IN EXHIBITION API
export const EXHIBITION_SORT_TYPE = 'EXHIBITION_SORT_TYPE';

// FILTER PRIZES IN EXHIBITION API

export const EXHIBITION_FILTER_TYPE = 'EXHIBITION_FILTER_TYPE';

// DATA FROM EXHIBITIONS API TO SHOW PRIZE LIST BY ID...
export const FETCH_EXHIBITION_BY_ID = 'FETCH_EXHIBITION_BY_ID';
export const FETCH_EXHIBITION_BY_ID_SUCCESS = 'FETCH_EXHIBITION_BY_ID_SUCCESS';
export const FETCH_EXHIBITION_BY_ID_ERROR = 'FETCH_EXHIBITION_BY_ID_ERROR';

// DATA FROM ART PRIZES TO DISPLAY ADVERTISEMENT BY ID ON ARTDESCRIPTION PAGE.......
export const FETCH_ADVERT_BY_ID = 'FETCH_ADVERT_BY_ID';
export const FETCH_ADVERT_BY_ID_SUCCESS = 'FETCH_ADVERT_BY_ID_SUCCESS';
export const FETCH_ADVERT_BY_ID_ERROR = 'FETCH_ADVERT_BY_ID_ERROR';

// INTENT TO ENTER COUNT ADD TO API BOOLEAN VALUE TRUE OR FALSE....
export const INTENT_TO_ENTER_PRIZES_BY_ID = 'INTENT_TO_ENTER_PRIZES';
export const INTENT_TO_ENTER_PRIZES_BY_ID_SUCCESS =
  'INTENT_TO_ENTER_PRIZES_BY_ID_SUCCESS';
export const INTENT_TO_ENTER_PRIZES_BY_ID_ERROR =
  'INTENT_TO_ENTER_PRIZES_BY_ID_ERROR';
// FOLLOW COUNT TO ADD TO API
export const FOLLOW_COUNT_PRIZES_BY_ID = 'FOLLOW_COUNT_PRIZES_BY_ID';
export const FOLLOW_COUNT_PRIZES_BY_ID_SUCCESS =
  'FOLLOW_COUNT_PRIZES_BY_ID_SUCCESS';
export const FOLLOW_COUNT_PRIZES_BY_ID_ERROR =
  'FOLLOW_COUNT_PRIZES_BY_ID_ERROR';

// INTENT TO ENTER COUNT ADD TO API BOOLEAN VALUE TRUE OR FALSE....
export const INTENT_TO_ENTER_EXHIBITIONS_BY_ID =
  'INTENT_TO_ENTER_EXHIBITIONS_BY_ID';
export const INTENT_TO_ENTER_EXHIBITIONS_BY_ID_SUCCESS =
  'INTENT_TO_ENTER_EXHIBITIONS_BY_ID_SUCCESS';
export const INTENT_TO_ENTER_EXHIBITIONS_BY_ID_ERROR =
  'INTENT_TO_ENTER_EXHIBITIONS_BY_ID_ERROR';

// FOLLOW COUNT TO ADD TO API
export const FOLLOW_COUNT_EXHIBITIONS_BY_ID = 'FOLLOW_COUNT_EXHIBITIONS_BY_ID';
export const FOLLOW_COUNT_EXHIBITIONS_BY_ID_SUCCESS =
  'FOLLOW_COUNT_EXHIBITIONS_BY_ID_SUCCESS';
export const FOLLOW_COUNT_EXHIBITIONS_BY_ID_ERROR =
  'FOLLOW_COUNT_EXHIBITIONS_BY_ID_ERROR';
