# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'artprizesnative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  # Pods for artprizesnative

  target 'artprizesnativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'artprizesnative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artprizesnative-tvOS

  target 'artprizesnative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
